language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install coveralls --use-wheel"
  - "pip install -r requirements-dev.pip --use-wheel"
  - "python setup.py install"
script:
  - coverage run --source=gdt `which nosetests` --verbose
after_success:
  - coveralls
