#!python

from gdt import cmdline

if __name__ == '__main__':
    # NOTE: argparse is insane
    parser = cmdline.get_parser()
    cmd_args = vars(parser.parse_args())

    dispatch = cmd_args.pop('dispatch')
    handler = cmdline.dispatch[dispatch]
    pipeline = handler(cmd_args)
    pipeline.process()
